use mizu;

INSERT INTO user (user_id, user_name, first_name, last_name, email, password, category_user, image)
VALUES (1,"Aaren","Cutmere","acutmere0","acutmere0@census.gov","bvgumHCIzr","admin","user_1.jpg"),
(2,"Ruby","Shields","rshields1","rshields1@bbc.co.uk","0nQtmB8","user","user_2.jpg"),
(3,"Amie","Pearmine","apearmine2","apearmine2@google.nl","L6DhZKvTWq","admin","user_3.jpg"),
(4,"Hervey","Laffin","hlaffin3","hlaffin3@friendfeed.com","t0DUpm","user","user_4.jpg"),
(5,"Tony","Radbond","tradbond4","tradbond4@godaddy.com","mkVC0UEau","user","user_5.jpg"),
(6,"Estrellita","Aberchirder","eaberchirder5","eaberchirder5@multiply.com","DXqDzt9","admin","user_6.jpg"),
(7,"Amalie","Butt","abutt6","abutt6@smugmug.com","slHZb5o5","admin","user_7.jpg"),
(8,"Winfield","Faulconbridge","wfaulconbridge7","wfaulconbridge7@com.com","iQAc4PoFucWF","user","user_8.jpg"),
(9,"Hebert","Bisson","hbisson8","hbisson8@typepad.com","DfNGzzq5yRa","admin","user_9.jpg"),
(10,"Helenka","Granleese","hgranleese9","hgranleese9@wix.com","VOjwiI","user","user_10.jpg"),
(11,"Natalina","Bynert","nbynerta","nbynerta@devhub.com","Bhzt3b9EbC2m","admin","user_11.jpg"),
(12,"Bettina","Calwell","bcalwellb","bcalwellb@infoseek.co.jp","KY8O0H","user","user_12.jpg"),
(13,"Anselma","Pexton","apextonc","apextonc@lycos.com","Y6KNRjR6l","admin","user_13.jpg"),
(14,"Wyatt","Biggadyke","wbiggadyked","wbiggadyked@opensource.org","gK1hTB2","admin","user_14.jpg"),
(15,"Jarrid","McVane","jmcvanee","jmcvanee@paginegialle.it","UFlpzx","user","user_15.jpg"),
(16,"Priscilla","Micklewicz","pmicklewiczf","pmicklewiczf@studiopress.com","YlmbgBToMA0","admin","user_16.jpg"),
(17,"Gerry","Geratt","ggerattg","ggerattg@opera.com","Av1VLRyf0wOC","admin","user_17.jpg"),
(18,"Ewan","Webb-Bowen","ewebbbowenh","ewebbbowenh@abc.net.au","ByvdHmzLaK","user","user_18.jpg"),
(19,"Odo","Towsey","otowseyi","otowseyi@craigslist.org","9rJX3xriY","admin","user_19.jpg"),
(20,"Allianora","Gives","agivesj","agivesj@wisc.edu","hola123","user","user_20.jpg"),
(21,"Rocco","Fodaro","roccofodaro","roccoelcapo@hotmail.com","AguanteBoca","user","p-1658118329297.png"),
(22,"Lionel Andres","Messiesta","messiesta","liomessiesta@juventuddeliniers.psg","VamosJuve","user","p-1658118583686.png"),
(23,"Lobo","Lobezno","lobo","lobo@gimnasia.wolf.txt","lobo","user","p-1658118763451.webp"),
(24,"asd","dasdan","asdasd","dadadas@dadasda.com.bra71L","asdasd","user","p-1658118909808.png"),
(25,"stefa","stefanini","piñita","stefa@xn--piita-pta.gob","1234","user","p-1658119011686.png"),
(26,"a","a","a","a@a.a","a","user","default.jpg"),
(27,"Lionel Andres","Messi","lio10dios","liomessiesta@juventuddeliniers.psg","$2a$10$06Me0tjIrsSDo7OPj5EuZOeBddf87asXHb97PIwSnyC/2LT95UnkO","user","default.jpg"),
(28,"Diego","Salvatore","diegos01","dms@dms.com.ar","$2a$10$5vKbIZqqpg5hbeOsmoWC.uiL5ez5EkFhIFhFqCT6nXgk2djoIQ3Ty","user","default.jpg"),
(29,"diego","salvatore","diago","dms@dms.net.ar","$2a$10$jA1yeHHJUz3FpSjBgfe6u.8fR.1EWeor/QLkuOm3UOSWU.Mrp2Vue","user","default.jpg"),
(30,"diego","salva","di","diego@dms.com.ar","$2a$10$kyqNshTNnF9HyJXyj5YUjunBFwKmAY3KBNmJXWxiEBAKNtklFXn4e","user","default.jpg");

 